name: livealandalus
favicon: null
layout_spectrum: 0.8302355927880853
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f9f3a'
    - '#0a6130'
    - '#fff4e6'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.8493248326703906
  lightness: 0.6323379979003221
  saturation: 0.6972553920932114
  rhythmicContrast: 0.03224516147747636
purpose: []
