name: livealandalus
favicon: null
layout_spectrum: 0.25902
typography_spectrum: 0.05487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fda01d'
    - '#fefefe'
    - '#fdca74'
    - '#843200'
  brandStrength: 0.8493248326703906
  lightness: 0.6323379979003221
  saturation: 0.6972553920932114
  rhythmicContrast: 0.03224516147747636
purpose: []
